name: Deploy preview on fly.io

on:
  pull_request:
    branches: [ main ]

jobs:
  staging_app:
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: bernsteinbear-com-pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: bernsteinbear-com-pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        if: ${{ github.event.action != 'closed' }}
        with:
          name: bernsteinbear-com-pr-${{ github.event.number }}
          region: ewr
          org: personal
        env:
          DOCKER_BUILDKIT: 1
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Clean up app
        if: ${{ github.event.action == 'closed' }}
        with:
          name: bernsteinbear-com-pr-${{ github.event.number }}
          region: ewr
          org: personal
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl app destroy --yes bernsteinbear-com-pr-${{ github.event.number }}
