name: Update build-env image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: docker build --target build_env --tag ghcr.io/tekknolagi/bernsteinbear-build-env .
      - name: push
        run: docker push ghcr.io/tekknolagi/bernsteinbear-build-env
