name: Update build-env image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: build
        run: docker build --target build_env .
      - name: push
        run: docker push ghcr.io/tekknolagi/bernsteinbear-build-env
